### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by juhacz** [luanon404/luanon#1]
I try installing library I got error:

```
(venv) PS V:\DEV\Projects\Python\carshelper> pip install https://github.com/luanon404/luanon/archive/refs/heads/main.zip
Collecting https://github.com/luanon404/luanon/archive/refs/heads/main.zip
  Downloading https://github.com/luanon404/luanon/archive/refs/heads/main.zip
     - 12.5 MB 395.1 kB/s 0:00:29
  Preparing metadata (setup.py) ... done
ERROR: No .egg-info directory found in C:\TEMP\pip-pip-egg-info-p7hevto4

```

**Comment by luanon404** [comment]
> I try installing library I got error:
> 
> ```
> (venv) PS V:\DEV\Projects\Python\carshelper> pip install https://github.com/luanon404/luanon/archive/refs/heads/main.zip
> Collecting https://github.com/luanon404/luanon/archive/refs/heads/main.zip
>   Downloading https://github.com/luanon404/luanon/archive/refs/heads/main.zip
>      - 12.5 MB 395.1 kB/s 0:00:29
>   Preparing metadata (setup.py) ... done
> ERROR: No .egg-info directory found in C:\TEMP\pip-pip-egg-info-p7hevto4
> 
> ```

yes, because this still building, so you cant install it
